### PR TITLE
Add command consumer

### PR DESCRIPTION
**Pull request by aguspina**

### CODE REVIEW

**Comment by aguspina** [comment]
Yup

**Comment by flbulgarelli** [comment]
@aguspina I think this is not a good idea, since if the command is not recognized, it will be lost forever. We should keep it in the queue, right?

**Comment by aguspina** [comment]
But if the command doesn't exists, the body doesn't have sense, am i wrong?

**Comment by flbulgarelli** [comment]
@aguspina ok, I have no big argument here against your proposal. Let's merge as-is

**Pull request merged**
